name: Deploy Treinazap - S3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/clt-action@v1
      - name: SET ENVS AGENT GIT HUB ACTIONS
        run: doppler secrets download --no-file --format=docker >> $GITHUB_ENV;
        env:
          TOKEN_DOPPLER: ${{ secrets.DOPPLER_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.21.0
      - name: SET ENV FIREBASE
        run: envsubst <srv/firebase-deploy.js> src/firebase.js
      - name: CHECK FILE
        run: cat src/firebase.js
      #- name: INSTALL AWS CLIENT
      #  run: pip install awscli
      - name: INSTALL E BUILD
        run: npm install && npm run build
        env:
           CI: "false"
      - name: DEPLOY S3
        run: cd build && AWS_ACCESS_KEY_ID=${ACCESS_KEY} AWS_SECRET_ACCESS_KEY=${SECRET_KEY} aws s3 sync . s3://zipzop --acl public-read --delete